[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["Gopkg.toml", "go.mod"]
auto-format = true
comment-token = "//"
language-servers =  ["gopls"]
indent = { tab-width = 4, unit = "\t" }
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
